//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ConfirmStatusTransferSoap", Namespace="http://tempuri.org/")]
public partial class ConfirmStatusTransfer : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback ExcuteOperationCompleted;
    
    /// <remarks/>
    public ConfirmStatusTransfer() {
        this.Url = System.Configuration.ConfigurationManager.AppSettings["ConfirmStatus_TransferWS.URL"];//"http://sandbox2.vtcebank.vn/PaygateAPI/PrivateService/ConfirmStatusTransfer.asmx";
    }
    
    /// <remarks/>
    public event ExcuteCompletedEventHandler ExcuteCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Excute", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Excute(string requestData, string dataSign) {
        object[] results = this.Invoke("Excute", new object[] {
                    requestData,
                    dataSign});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginExcute(string requestData, string dataSign, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Excute", new object[] {
                    requestData,
                    dataSign}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndExcute(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ExcuteAsync(string requestData, string dataSign) {
        this.ExcuteAsync(requestData, dataSign, null);
    }
    
    /// <remarks/>
    public void ExcuteAsync(string requestData, string dataSign, object userState) {
        if ((this.ExcuteOperationCompleted == null)) {
            this.ExcuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcuteOperationCompleted);
        }
        this.InvokeAsync("Excute", new object[] {
                    requestData,
                    dataSign}, this.ExcuteOperationCompleted, userState);
    }
    
    private void OnExcuteOperationCompleted(object arg) {
        if ((this.ExcuteCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ExcuteCompleted(this, new ExcuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void ExcuteCompletedEventHandler(object sender, ExcuteCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ExcuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ExcuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
