//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 

namespace Paygate.Utility
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ConfigSMSSoap", Namespace = "http://tempuri.org/")]
    public partial class ConfigSMS : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback GetSystemSMSOperationCompleted;

        private System.Threading.SendOrPostCallback SetSystemSMSOperationCompleted;

        private System.Threading.SendOrPostCallback ControlSMSOperationCompleted;

        private System.Threading.SendOrPostCallback GetListODPOperationCompleted;

        private System.Threading.SendOrPostCallback ResendODPOperationCompleted;

        /// <remarks/>
        public ConfigSMS()
        {
            this.Url = System.Configuration.ConfigurationManager.AppSettings["Service_ConfigSMS"] ?? "http://117.103.205.38:8088/odpservices/ConfigSMS.asmx"; 
        }

        /// <remarks/>
        public event GetSystemSMSCompletedEventHandler GetSystemSMSCompleted;

        /// <remarks/>
        public event SetSystemSMSCompletedEventHandler SetSystemSMSCompleted;

        /// <remarks/>
        public event ControlSMSCompletedEventHandler ControlSMSCompleted;

        /// <remarks/>
        public event GetListODPCompletedEventHandler GetListODPCompleted;

        /// <remarks/>
        public event ResendODPCompletedEventHandler ResendODPCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSystemSMS", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSystemSMS()
        {
            object[] results = this.Invoke("GetSystemSMS", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetSystemSMS(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetSystemSMS", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndGetSystemSMS(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetSystemSMSAsync()
        {
            this.GetSystemSMSAsync(null);
        }

        /// <remarks/>
        public void GetSystemSMSAsync(object userState)
        {
            if ((this.GetSystemSMSOperationCompleted == null))
            {
                this.GetSystemSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSystemSMSOperationCompleted);
            }
            this.InvokeAsync("GetSystemSMS", new object[0], this.GetSystemSMSOperationCompleted, userState);
        }

        private void OnGetSystemSMSOperationCompleted(object arg)
        {
            if ((this.GetSystemSMSCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSystemSMSCompleted(this, new GetSystemSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetSystemSMS", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SetSystemSMS(string systemSMS)
        {
            object[] results = this.Invoke("SetSystemSMS", new object[] {
                    systemSMS});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSetSystemSMS(string systemSMS, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SetSystemSMS", new object[] {
                    systemSMS}, callback, asyncState);
        }

        /// <remarks/>
        public int EndSetSystemSMS(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public void SetSystemSMSAsync(string systemSMS)
        {
            this.SetSystemSMSAsync(systemSMS, null);
        }

        /// <remarks/>
        public void SetSystemSMSAsync(string systemSMS, object userState)
        {
            if ((this.SetSystemSMSOperationCompleted == null))
            {
                this.SetSystemSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSystemSMSOperationCompleted);
            }
            this.InvokeAsync("SetSystemSMS", new object[] {
                    systemSMS}, this.SetSystemSMSOperationCompleted, userState);
        }

        private void OnSetSystemSMSOperationCompleted(object arg)
        {
            if ((this.SetSystemSMSCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSystemSMSCompleted(this, new SetSystemSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ControlSMS", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ControlSMS(string Mobile, string oMessage)
        {
            object[] results = this.Invoke("ControlSMS", new object[] {
                    Mobile,
                    oMessage});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginControlSMS(string Mobile, string oMessage, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ControlSMS", new object[] {
                    Mobile,
                    oMessage}, callback, asyncState);
        }

        /// <remarks/>
        public string EndControlSMS(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ControlSMSAsync(string Mobile, string oMessage)
        {
            this.ControlSMSAsync(Mobile, oMessage, null);
        }

        /// <remarks/>
        public void ControlSMSAsync(string Mobile, string oMessage, object userState)
        {
            if ((this.ControlSMSOperationCompleted == null))
            {
                this.ControlSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnControlSMSOperationCompleted);
            }
            this.InvokeAsync("ControlSMS", new object[] {
                    Mobile,
                    oMessage}, this.ControlSMSOperationCompleted, userState);
        }

        private void OnControlSMSOperationCompleted(object arg)
        {
            if ((this.ControlSMSCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ControlSMSCompleted(this, new ControlSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListODP", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetListODP(string AccountName)
        {
            object[] results = this.Invoke("GetListODP", new object[] {
                    AccountName});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetListODP(string AccountName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetListODP", new object[] {
                    AccountName}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetListODP(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetListODPAsync(string AccountName)
        {
            this.GetListODPAsync(AccountName, null);
        }

        /// <remarks/>
        public void GetListODPAsync(string AccountName, object userState)
        {
            if ((this.GetListODPOperationCompleted == null))
            {
                this.GetListODPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListODPOperationCompleted);
            }
            this.InvokeAsync("GetListODP", new object[] {
                    AccountName}, this.GetListODPOperationCompleted, userState);
        }

        private void OnGetListODPOperationCompleted(object arg)
        {
            if ((this.GetListODPCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListODPCompleted(this, new GetListODPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResendODP", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ResendODP(string AccountName)
        {
            object[] results = this.Invoke("ResendODP", new object[] {
                    AccountName});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginResendODP(string AccountName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ResendODP", new object[] {
                    AccountName}, callback, asyncState);
        }

        /// <remarks/>
        public string EndResendODP(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ResendODPAsync(string AccountName)
        {
            this.ResendODPAsync(AccountName, null);
        }

        /// <remarks/>
        public void ResendODPAsync(string AccountName, object userState)
        {
            if ((this.ResendODPOperationCompleted == null))
            {
                this.ResendODPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResendODPOperationCompleted);
            }
            this.InvokeAsync("ResendODP", new object[] {
                    AccountName}, this.ResendODPOperationCompleted, userState);
        }

        private void OnResendODPOperationCompleted(object arg)
        {
            if ((this.ResendODPCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResendODPCompleted(this, new ResendODPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void GetSystemSMSCompletedEventHandler(object sender, GetSystemSMSCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSystemSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetSystemSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void SetSystemSMSCompletedEventHandler(object sender, SetSystemSMSCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSystemSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SetSystemSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void ControlSMSCompletedEventHandler(object sender, ControlSMSCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ControlSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ControlSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void GetListODPCompletedEventHandler(object sender, GetListODPCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListODPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetListODPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void ResendODPCompletedEventHandler(object sender, ResendODPCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResendODPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ResendODPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}