//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 

namespace Paygate.Utility.Services
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "GetCardsSoap", Namespace = "http://tempuri.org/")]
    public partial class GetCards : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback BuyCardSteamWalletOperationCompleted;

        private System.Threading.SendOrPostCallback GetCardSteamWalletOperationCompleted;

        /// <remarks/>
        public GetCards()
        {
            this.Url = System.Configuration.ConfigurationManager.AppSettings["SteamWallet_WS_URL"];// "http://sandbox3.vtcebank.vn/steamwallet/GetCards.asmx";
        }

        /// <remarks/>
        public event BuyCardSteamWalletCompletedEventHandler BuyCardSteamWalletCompleted;

        /// <remarks/>
        public event GetCardSteamWalletCompletedEventHandler GetCardSteamWalletCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuyCardSteamWallet", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BuyCardSteamWallet(string partnerCode, int partnerTransactionID, string accountName, int amount, int quantity, string cardType, string sign)
        {
            object[] results = this.Invoke("BuyCardSteamWallet", new object[] {
                    partnerCode,
                    partnerTransactionID,
                    accountName,
                    amount,
                    quantity,
                    cardType,
                    sign});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginBuyCardSteamWallet(string partnerCode, int partnerTransactionID, string accountName, int amount, int quantity, string cardType, string sign, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("BuyCardSteamWallet", new object[] {
                    partnerCode,
                    partnerTransactionID,
                    accountName,
                    amount,
                    quantity,
                    cardType,
                    sign}, callback, asyncState);
        }

        /// <remarks/>
        public string EndBuyCardSteamWallet(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void BuyCardSteamWalletAsync(string partnerCode, int partnerTransactionID, string accountName, int amount, int quantity, string cardType, string sign)
        {
            this.BuyCardSteamWalletAsync(partnerCode, partnerTransactionID, accountName, amount, quantity, cardType, sign, null);
        }

        /// <remarks/>
        public void BuyCardSteamWalletAsync(string partnerCode, int partnerTransactionID, string accountName, int amount, int quantity, string cardType, string sign, object userState)
        {
            if ((this.BuyCardSteamWalletOperationCompleted == null))
            {
                this.BuyCardSteamWalletOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuyCardSteamWalletOperationCompleted);
            }
            this.InvokeAsync("BuyCardSteamWallet", new object[] {
                    partnerCode,
                    partnerTransactionID,
                    accountName,
                    amount,
                    quantity,
                    cardType,
                    sign}, this.BuyCardSteamWalletOperationCompleted, userState);
        }

        private void OnBuyCardSteamWalletOperationCompleted(object arg)
        {
            if ((this.BuyCardSteamWalletCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuyCardSteamWalletCompleted(this, new BuyCardSteamWalletCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCardSteamWallet", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCardSteamWallet(string partnerCode, int partnerTransactionID, string accountName, string sign)
        {
            object[] results = this.Invoke("GetCardSteamWallet", new object[] {
                    partnerCode,
                    partnerTransactionID,
                    accountName,
                    sign});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetCardSteamWallet(string partnerCode, int partnerTransactionID, string accountName, string sign, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetCardSteamWallet", new object[] {
                    partnerCode,
                    partnerTransactionID,
                    accountName,
                    sign}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetCardSteamWallet(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetCardSteamWalletAsync(string partnerCode, int partnerTransactionID, string accountName, string sign)
        {
            this.GetCardSteamWalletAsync(partnerCode, partnerTransactionID, accountName, sign, null);
        }

        /// <remarks/>
        public void GetCardSteamWalletAsync(string partnerCode, int partnerTransactionID, string accountName, string sign, object userState)
        {
            if ((this.GetCardSteamWalletOperationCompleted == null))
            {
                this.GetCardSteamWalletOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCardSteamWalletOperationCompleted);
            }
            this.InvokeAsync("GetCardSteamWallet", new object[] {
                    partnerCode,
                    partnerTransactionID,
                    accountName,
                    sign}, this.GetCardSteamWalletOperationCompleted, userState);
        }

        private void OnGetCardSteamWalletOperationCompleted(object arg)
        {
            if ((this.GetCardSteamWalletCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCardSteamWalletCompleted(this, new GetCardSteamWalletCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void BuyCardSteamWalletCompletedEventHandler(object sender, BuyCardSteamWalletCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuyCardSteamWalletCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal BuyCardSteamWalletCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void GetCardSteamWalletCompletedEventHandler(object sender, GetCardSteamWalletCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCardSteamWalletCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetCardSteamWalletCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}