//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Configuration;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="GoodsPaygateSoap", Namespace="http://tempuri.org/")]
public partial class GoodsPaygate : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback RequestTransactionOperationCompleted;
    
    /// <remarks/>
    public GoodsPaygate() {
        this.Url = ConfigurationManager.AppSettings["TOPUP_CDT.URL"] ?? "http://sandbox2.vtcebank.vn/PaygateAPI/PublicService/GoodsPaygate.asmx";
    }
    
    /// <remarks/>
    public event RequestTransactionCompletedEventHandler RequestTransactionCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string RequestTransaction(string requesData, string partnerCode, string commandType, string version) {
        object[] results = this.Invoke("RequestTransaction", new object[] {
                    requesData,
                    partnerCode,
                    commandType,
                    version});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRequestTransaction(string requesData, string partnerCode, string commandType, string version, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RequestTransaction", new object[] {
                    requesData,
                    partnerCode,
                    commandType,
                    version}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndRequestTransaction(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void RequestTransactionAsync(string requesData, string partnerCode, string commandType, string version) {
        this.RequestTransactionAsync(requesData, partnerCode, commandType, version, null);
    }
    
    /// <remarks/>
    public void RequestTransactionAsync(string requesData, string partnerCode, string commandType, string version, object userState) {
        if ((this.RequestTransactionOperationCompleted == null)) {
            this.RequestTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestTransactionOperationCompleted);
        }
        this.InvokeAsync("RequestTransaction", new object[] {
                    requesData,
                    partnerCode,
                    commandType,
                    version}, this.RequestTransactionOperationCompleted, userState);
    }
    
    private void OnRequestTransactionOperationCompleted(object arg) {
        if ((this.RequestTransactionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RequestTransactionCompleted(this, new RequestTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void RequestTransactionCompletedEventHandler(object sender, RequestTransactionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RequestTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RequestTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
