//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="VTCBillAPISoap", Namespace="http://tempuri.org/")]
public partial class VTCBillAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetBillsOperationCompleted;
    
    private System.Threading.SendOrPostCallback OnlineBillPaymentOperationCompleted;
    
    private System.Threading.SendOrPostCallback OnlineBillPayment4KioskOperationCompleted;
    
    private System.Threading.SendOrPostCallback OfflineBillPaymentOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetUserTransactionListOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetTransactionStatusOperationCompleted;
    
    private System.Threading.SendOrPostCallback AddAutoBillRemindOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateAutoBillRemindOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetBillRegistedListOperationCompleted;
    
    private System.Threading.SendOrPostCallback AddAutoBillPaymentOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateAutoBillPaymentOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetServicesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetProvidersOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetTransactionDetailOperationCompleted;
    
    /// <remarks/>
    public VTCBillAPI() {
        this.Url = System.Configuration.ConfigurationManager.AppSettings["BILL.URL"];// "http://sandbox2.vtcebank.vn/VTCBillService/VTCBillAPI.asmx";
    }
    
    /// <remarks/>
    public event GetBillsCompletedEventHandler GetBillsCompleted;
    
    /// <remarks/>
    public event OnlineBillPaymentCompletedEventHandler OnlineBillPaymentCompleted;
    
    /// <remarks/>
    public event OnlineBillPayment4KioskCompletedEventHandler OnlineBillPayment4KioskCompleted;
    
    /// <remarks/>
    public event OfflineBillPaymentCompletedEventHandler OfflineBillPaymentCompleted;
    
    /// <remarks/>
    public event GetUserTransactionListCompletedEventHandler GetUserTransactionListCompleted;
    
    /// <remarks/>
    public event GetTransactionStatusCompletedEventHandler GetTransactionStatusCompleted;
    
    /// <remarks/>
    public event AddAutoBillRemindCompletedEventHandler AddAutoBillRemindCompleted;
    
    /// <remarks/>
    public event UpdateAutoBillRemindCompletedEventHandler UpdateAutoBillRemindCompleted;
    
    /// <remarks/>
    public event GetBillRegistedListCompletedEventHandler GetBillRegistedListCompleted;
    
    /// <remarks/>
    public event AddAutoBillPaymentCompletedEventHandler AddAutoBillPaymentCompleted;
    
    /// <remarks/>
    public event UpdateAutoBillPaymentCompletedEventHandler UpdateAutoBillPaymentCompleted;
    
    /// <remarks/>
    public event GetServicesCompletedEventHandler GetServicesCompleted;
    
    /// <remarks/>
    public event GetProvidersCompletedEventHandler GetProvidersCompleted;
    
    /// <remarks/>
    public event GetTransactionDetailCompletedEventHandler GetTransactionDetailCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBills", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse GetBills(string customerId, string userId, string serviceId, string providerId, string capcha, string merchantID, string encryptData, string area, string houseNumber) {
        object[] results = this.Invoke("GetBills", new object[] {
                    customerId,
                    userId,
                    serviceId,
                    providerId,
                    capcha,
                    merchantID,
                    encryptData,
                    area,
                    houseNumber});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetBills(string customerId, string userId, string serviceId, string providerId, string capcha, string merchantID, string encryptData, string area, string houseNumber, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetBills", new object[] {
                    customerId,
                    userId,
                    serviceId,
                    providerId,
                    capcha,
                    merchantID,
                    encryptData,
                    area,
                    houseNumber}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndGetBills(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void GetBillsAsync(string customerId, string userId, string serviceId, string providerId, string capcha, string merchantID, string encryptData, string area, string houseNumber) {
        this.GetBillsAsync(customerId, userId, serviceId, providerId, capcha, merchantID, encryptData, area, houseNumber, null);
    }
    
    /// <remarks/>
    public void GetBillsAsync(string customerId, string userId, string serviceId, string providerId, string capcha, string merchantID, string encryptData, string area, string houseNumber, object userState) {
        if ((this.GetBillsOperationCompleted == null)) {
            this.GetBillsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBillsOperationCompleted);
        }
        this.InvokeAsync("GetBills", new object[] {
                    customerId,
                    userId,
                    serviceId,
                    providerId,
                    capcha,
                    merchantID,
                    encryptData,
                    area,
                    houseNumber}, this.GetBillsOperationCompleted, userState);
    }
    
    private void OnGetBillsOperationCompleted(object arg) {
        if ((this.GetBillsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetBillsCompleted(this, new GetBillsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OnlineBillPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse OnlineBillPayment(PayOnlineBillRequest payRequest, string merchantID, string encryptData) {
        object[] results = this.Invoke("OnlineBillPayment", new object[] {
                    payRequest,
                    merchantID,
                    encryptData});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginOnlineBillPayment(PayOnlineBillRequest payRequest, string merchantID, string encryptData, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("OnlineBillPayment", new object[] {
                    payRequest,
                    merchantID,
                    encryptData}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndOnlineBillPayment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void OnlineBillPaymentAsync(PayOnlineBillRequest payRequest, string merchantID, string encryptData) {
        this.OnlineBillPaymentAsync(payRequest, merchantID, encryptData, null);
    }
    
    /// <remarks/>
    public void OnlineBillPaymentAsync(PayOnlineBillRequest payRequest, string merchantID, string encryptData, object userState) {
        if ((this.OnlineBillPaymentOperationCompleted == null)) {
            this.OnlineBillPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOnlineBillPaymentOperationCompleted);
        }
        this.InvokeAsync("OnlineBillPayment", new object[] {
                    payRequest,
                    merchantID,
                    encryptData}, this.OnlineBillPaymentOperationCompleted, userState);
    }
    
    private void OnOnlineBillPaymentOperationCompleted(object arg) {
        if ((this.OnlineBillPaymentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.OnlineBillPaymentCompleted(this, new OnlineBillPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OnlineBillPayment4Kiosk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse OnlineBillPayment4Kiosk(PayOnlineBillRequest payRequest, string merchantID, string kioskId, string encryptData) {
        object[] results = this.Invoke("OnlineBillPayment4Kiosk", new object[] {
                    payRequest,
                    merchantID,
                    kioskId,
                    encryptData});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginOnlineBillPayment4Kiosk(PayOnlineBillRequest payRequest, string merchantID, string kioskId, string encryptData, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("OnlineBillPayment4Kiosk", new object[] {
                    payRequest,
                    merchantID,
                    kioskId,
                    encryptData}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndOnlineBillPayment4Kiosk(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void OnlineBillPayment4KioskAsync(PayOnlineBillRequest payRequest, string merchantID, string kioskId, string encryptData) {
        this.OnlineBillPayment4KioskAsync(payRequest, merchantID, kioskId, encryptData, null);
    }
    
    /// <remarks/>
    public void OnlineBillPayment4KioskAsync(PayOnlineBillRequest payRequest, string merchantID, string kioskId, string encryptData, object userState) {
        if ((this.OnlineBillPayment4KioskOperationCompleted == null)) {
            this.OnlineBillPayment4KioskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOnlineBillPayment4KioskOperationCompleted);
        }
        this.InvokeAsync("OnlineBillPayment4Kiosk", new object[] {
                    payRequest,
                    merchantID,
                    kioskId,
                    encryptData}, this.OnlineBillPayment4KioskOperationCompleted, userState);
    }
    
    private void OnOnlineBillPayment4KioskOperationCompleted(object arg) {
        if ((this.OnlineBillPayment4KioskCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.OnlineBillPayment4KioskCompleted(this, new OnlineBillPayment4KioskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OfflineBillPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse OfflineBillPayment(PayOfflineBillRequest offlineBillRequest, string merchantID, string encryptData) {
        object[] results = this.Invoke("OfflineBillPayment", new object[] {
                    offlineBillRequest,
                    merchantID,
                    encryptData});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginOfflineBillPayment(PayOfflineBillRequest offlineBillRequest, string merchantID, string encryptData, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("OfflineBillPayment", new object[] {
                    offlineBillRequest,
                    merchantID,
                    encryptData}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndOfflineBillPayment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void OfflineBillPaymentAsync(PayOfflineBillRequest offlineBillRequest, string merchantID, string encryptData) {
        this.OfflineBillPaymentAsync(offlineBillRequest, merchantID, encryptData, null);
    }
    
    /// <remarks/>
    public void OfflineBillPaymentAsync(PayOfflineBillRequest offlineBillRequest, string merchantID, string encryptData, object userState) {
        if ((this.OfflineBillPaymentOperationCompleted == null)) {
            this.OfflineBillPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOfflineBillPaymentOperationCompleted);
        }
        this.InvokeAsync("OfflineBillPayment", new object[] {
                    offlineBillRequest,
                    merchantID,
                    encryptData}, this.OfflineBillPaymentOperationCompleted, userState);
    }
    
    private void OnOfflineBillPaymentOperationCompleted(object arg) {
        if ((this.OfflineBillPaymentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.OfflineBillPaymentCompleted(this, new OfflineBillPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserTransactionList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse GetUserTransactionList(string userId, string orderNo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> autoPaymentCondition, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> transStatusCondition, string fromDate, string toDate, string merchantID, string encryptData) {
        object[] results = this.Invoke("GetUserTransactionList", new object[] {
                    userId,
                    orderNo,
                    autoPaymentCondition,
                    transStatusCondition,
                    fromDate,
                    toDate,
                    merchantID,
                    encryptData});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetUserTransactionList(string userId, string orderNo, System.Nullable<int> autoPaymentCondition, System.Nullable<int> transStatusCondition, string fromDate, string toDate, string merchantID, string encryptData, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetUserTransactionList", new object[] {
                    userId,
                    orderNo,
                    autoPaymentCondition,
                    transStatusCondition,
                    fromDate,
                    toDate,
                    merchantID,
                    encryptData}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndGetUserTransactionList(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void GetUserTransactionListAsync(string userId, string orderNo, System.Nullable<int> autoPaymentCondition, System.Nullable<int> transStatusCondition, string fromDate, string toDate, string merchantID, string encryptData) {
        this.GetUserTransactionListAsync(userId, orderNo, autoPaymentCondition, transStatusCondition, fromDate, toDate, merchantID, encryptData, null);
    }
    
    /// <remarks/>
    public void GetUserTransactionListAsync(string userId, string orderNo, System.Nullable<int> autoPaymentCondition, System.Nullable<int> transStatusCondition, string fromDate, string toDate, string merchantID, string encryptData, object userState) {
        if ((this.GetUserTransactionListOperationCompleted == null)) {
            this.GetUserTransactionListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserTransactionListOperationCompleted);
        }
        this.InvokeAsync("GetUserTransactionList", new object[] {
                    userId,
                    orderNo,
                    autoPaymentCondition,
                    transStatusCondition,
                    fromDate,
                    toDate,
                    merchantID,
                    encryptData}, this.GetUserTransactionListOperationCompleted, userState);
    }
    
    private void OnGetUserTransactionListOperationCompleted(object arg) {
        if ((this.GetUserTransactionListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetUserTransactionListCompleted(this, new GetUserTransactionListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTransactionStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse GetTransactionStatus(string invoiceNo, string requestTime, string merchantID, string encryptData, string payooTransID) {
        object[] results = this.Invoke("GetTransactionStatus", new object[] {
                    invoiceNo,
                    requestTime,
                    merchantID,
                    encryptData,
                    payooTransID});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetTransactionStatus(string invoiceNo, string requestTime, string merchantID, string encryptData, string payooTransID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetTransactionStatus", new object[] {
                    invoiceNo,
                    requestTime,
                    merchantID,
                    encryptData,
                    payooTransID}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndGetTransactionStatus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void GetTransactionStatusAsync(string invoiceNo, string requestTime, string merchantID, string encryptData, string payooTransID) {
        this.GetTransactionStatusAsync(invoiceNo, requestTime, merchantID, encryptData, payooTransID, null);
    }
    
    /// <remarks/>
    public void GetTransactionStatusAsync(string invoiceNo, string requestTime, string merchantID, string encryptData, string payooTransID, object userState) {
        if ((this.GetTransactionStatusOperationCompleted == null)) {
            this.GetTransactionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionStatusOperationCompleted);
        }
        this.InvokeAsync("GetTransactionStatus", new object[] {
                    invoiceNo,
                    requestTime,
                    merchantID,
                    encryptData,
                    payooTransID}, this.GetTransactionStatusOperationCompleted, userState);
    }
    
    private void OnGetTransactionStatusOperationCompleted(object arg) {
        if ((this.GetTransactionStatusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetTransactionStatusCompleted(this, new GetTransactionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddAutoBillRemind", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse AddAutoBillRemind(AutoBillRemindRequest autoRemindRequest, string merchantID, string encryptData) {
        object[] results = this.Invoke("AddAutoBillRemind", new object[] {
                    autoRemindRequest,
                    merchantID,
                    encryptData});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAddAutoBillRemind(AutoBillRemindRequest autoRemindRequest, string merchantID, string encryptData, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AddAutoBillRemind", new object[] {
                    autoRemindRequest,
                    merchantID,
                    encryptData}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndAddAutoBillRemind(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void AddAutoBillRemindAsync(AutoBillRemindRequest autoRemindRequest, string merchantID, string encryptData) {
        this.AddAutoBillRemindAsync(autoRemindRequest, merchantID, encryptData, null);
    }
    
    /// <remarks/>
    public void AddAutoBillRemindAsync(AutoBillRemindRequest autoRemindRequest, string merchantID, string encryptData, object userState) {
        if ((this.AddAutoBillRemindOperationCompleted == null)) {
            this.AddAutoBillRemindOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAutoBillRemindOperationCompleted);
        }
        this.InvokeAsync("AddAutoBillRemind", new object[] {
                    autoRemindRequest,
                    merchantID,
                    encryptData}, this.AddAutoBillRemindOperationCompleted, userState);
    }
    
    private void OnAddAutoBillRemindOperationCompleted(object arg) {
        if ((this.AddAutoBillRemindCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AddAutoBillRemindCompleted(this, new AddAutoBillRemindCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateAutoBillRemind", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse UpdateAutoBillRemind(MerchantAutoBillRemindRequest merchantAutoRemindRequest, string merchantID, string encryptData) {
        object[] results = this.Invoke("UpdateAutoBillRemind", new object[] {
                    merchantAutoRemindRequest,
                    merchantID,
                    encryptData});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateAutoBillRemind(MerchantAutoBillRemindRequest merchantAutoRemindRequest, string merchantID, string encryptData, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateAutoBillRemind", new object[] {
                    merchantAutoRemindRequest,
                    merchantID,
                    encryptData}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndUpdateAutoBillRemind(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateAutoBillRemindAsync(MerchantAutoBillRemindRequest merchantAutoRemindRequest, string merchantID, string encryptData) {
        this.UpdateAutoBillRemindAsync(merchantAutoRemindRequest, merchantID, encryptData, null);
    }
    
    /// <remarks/>
    public void UpdateAutoBillRemindAsync(MerchantAutoBillRemindRequest merchantAutoRemindRequest, string merchantID, string encryptData, object userState) {
        if ((this.UpdateAutoBillRemindOperationCompleted == null)) {
            this.UpdateAutoBillRemindOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAutoBillRemindOperationCompleted);
        }
        this.InvokeAsync("UpdateAutoBillRemind", new object[] {
                    merchantAutoRemindRequest,
                    merchantID,
                    encryptData}, this.UpdateAutoBillRemindOperationCompleted, userState);
    }
    
    private void OnUpdateAutoBillRemindOperationCompleted(object arg) {
        if ((this.UpdateAutoBillRemindCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateAutoBillRemindCompleted(this, new UpdateAutoBillRemindCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBillRegistedList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse GetBillRegistedList(GetBillRegistedList getBillRegList, string merchantID, string encryptData) {
        object[] results = this.Invoke("GetBillRegistedList", new object[] {
                    getBillRegList,
                    merchantID,
                    encryptData});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetBillRegistedList(GetBillRegistedList getBillRegList, string merchantID, string encryptData, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetBillRegistedList", new object[] {
                    getBillRegList,
                    merchantID,
                    encryptData}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndGetBillRegistedList(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void GetBillRegistedListAsync(GetBillRegistedList getBillRegList, string merchantID, string encryptData) {
        this.GetBillRegistedListAsync(getBillRegList, merchantID, encryptData, null);
    }
    
    /// <remarks/>
    public void GetBillRegistedListAsync(GetBillRegistedList getBillRegList, string merchantID, string encryptData, object userState) {
        if ((this.GetBillRegistedListOperationCompleted == null)) {
            this.GetBillRegistedListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBillRegistedListOperationCompleted);
        }
        this.InvokeAsync("GetBillRegistedList", new object[] {
                    getBillRegList,
                    merchantID,
                    encryptData}, this.GetBillRegistedListOperationCompleted, userState);
    }
    
    private void OnGetBillRegistedListOperationCompleted(object arg) {
        if ((this.GetBillRegistedListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetBillRegistedListCompleted(this, new GetBillRegistedListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddAutoBillPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse AddAutoBillPayment(AutoBillPaymentRequest autoBillPayment, string merchantID, string encryptData) {
        object[] results = this.Invoke("AddAutoBillPayment", new object[] {
                    autoBillPayment,
                    merchantID,
                    encryptData});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAddAutoBillPayment(AutoBillPaymentRequest autoBillPayment, string merchantID, string encryptData, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AddAutoBillPayment", new object[] {
                    autoBillPayment,
                    merchantID,
                    encryptData}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndAddAutoBillPayment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void AddAutoBillPaymentAsync(AutoBillPaymentRequest autoBillPayment, string merchantID, string encryptData) {
        this.AddAutoBillPaymentAsync(autoBillPayment, merchantID, encryptData, null);
    }
    
    /// <remarks/>
    public void AddAutoBillPaymentAsync(AutoBillPaymentRequest autoBillPayment, string merchantID, string encryptData, object userState) {
        if ((this.AddAutoBillPaymentOperationCompleted == null)) {
            this.AddAutoBillPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAutoBillPaymentOperationCompleted);
        }
        this.InvokeAsync("AddAutoBillPayment", new object[] {
                    autoBillPayment,
                    merchantID,
                    encryptData}, this.AddAutoBillPaymentOperationCompleted, userState);
    }
    
    private void OnAddAutoBillPaymentOperationCompleted(object arg) {
        if ((this.AddAutoBillPaymentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AddAutoBillPaymentCompleted(this, new AddAutoBillPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateAutoBillPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse UpdateAutoBillPayment(MerchantSetAutoBillPaymentRequest merchantAutoRemindRequest, string merchantID, string encryptData) {
        object[] results = this.Invoke("UpdateAutoBillPayment", new object[] {
                    merchantAutoRemindRequest,
                    merchantID,
                    encryptData});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateAutoBillPayment(MerchantSetAutoBillPaymentRequest merchantAutoRemindRequest, string merchantID, string encryptData, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateAutoBillPayment", new object[] {
                    merchantAutoRemindRequest,
                    merchantID,
                    encryptData}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndUpdateAutoBillPayment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateAutoBillPaymentAsync(MerchantSetAutoBillPaymentRequest merchantAutoRemindRequest, string merchantID, string encryptData) {
        this.UpdateAutoBillPaymentAsync(merchantAutoRemindRequest, merchantID, encryptData, null);
    }
    
    /// <remarks/>
    public void UpdateAutoBillPaymentAsync(MerchantSetAutoBillPaymentRequest merchantAutoRemindRequest, string merchantID, string encryptData, object userState) {
        if ((this.UpdateAutoBillPaymentOperationCompleted == null)) {
            this.UpdateAutoBillPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAutoBillPaymentOperationCompleted);
        }
        this.InvokeAsync("UpdateAutoBillPayment", new object[] {
                    merchantAutoRemindRequest,
                    merchantID,
                    encryptData}, this.UpdateAutoBillPaymentOperationCompleted, userState);
    }
    
    private void OnUpdateAutoBillPaymentOperationCompleted(object arg) {
        if ((this.UpdateAutoBillPaymentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateAutoBillPaymentCompleted(this, new UpdateAutoBillPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetServices", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse GetServices(string userId, string merchantID, string encryptData) {
        object[] results = this.Invoke("GetServices", new object[] {
                    userId,
                    merchantID,
                    encryptData});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetServices(string userId, string merchantID, string encryptData, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetServices", new object[] {
                    userId,
                    merchantID,
                    encryptData}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndGetServices(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void GetServicesAsync(string userId, string merchantID, string encryptData) {
        this.GetServicesAsync(userId, merchantID, encryptData, null);
    }
    
    /// <remarks/>
    public void GetServicesAsync(string userId, string merchantID, string encryptData, object userState) {
        if ((this.GetServicesOperationCompleted == null)) {
            this.GetServicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServicesOperationCompleted);
        }
        this.InvokeAsync("GetServices", new object[] {
                    userId,
                    merchantID,
                    encryptData}, this.GetServicesOperationCompleted, userState);
    }
    
    private void OnGetServicesOperationCompleted(object arg) {
        if ((this.GetServicesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetServicesCompleted(this, new GetServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProviders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse GetProviders(string userId, string merchantID, string encryptData) {
        object[] results = this.Invoke("GetProviders", new object[] {
                    userId,
                    merchantID,
                    encryptData});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetProviders(string userId, string merchantID, string encryptData, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetProviders", new object[] {
                    userId,
                    merchantID,
                    encryptData}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndGetProviders(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void GetProvidersAsync(string userId, string merchantID, string encryptData) {
        this.GetProvidersAsync(userId, merchantID, encryptData, null);
    }
    
    /// <remarks/>
    public void GetProvidersAsync(string userId, string merchantID, string encryptData, object userState) {
        if ((this.GetProvidersOperationCompleted == null)) {
            this.GetProvidersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProvidersOperationCompleted);
        }
        this.InvokeAsync("GetProviders", new object[] {
                    userId,
                    merchantID,
                    encryptData}, this.GetProvidersOperationCompleted, userState);
    }
    
    private void OnGetProvidersOperationCompleted(object arg) {
        if ((this.GetProvidersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetProvidersCompleted(this, new GetProvidersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTransactionDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VTCGWReponse GetTransactionDetail(string OrderNo, string merchantID, string encryptData) {
        object[] results = this.Invoke("GetTransactionDetail", new object[] {
                    OrderNo,
                    merchantID,
                    encryptData});
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetTransactionDetail(string OrderNo, string merchantID, string encryptData, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetTransactionDetail", new object[] {
                    OrderNo,
                    merchantID,
                    encryptData}, callback, asyncState);
    }
    
    /// <remarks/>
    public VTCGWReponse EndGetTransactionDetail(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((VTCGWReponse)(results[0]));
    }
    
    /// <remarks/>
    public void GetTransactionDetailAsync(string OrderNo, string merchantID, string encryptData) {
        this.GetTransactionDetailAsync(OrderNo, merchantID, encryptData, null);
    }
    
    /// <remarks/>
    public void GetTransactionDetailAsync(string OrderNo, string merchantID, string encryptData, object userState) {
        if ((this.GetTransactionDetailOperationCompleted == null)) {
            this.GetTransactionDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionDetailOperationCompleted);
        }
        this.InvokeAsync("GetTransactionDetail", new object[] {
                    OrderNo,
                    merchantID,
                    encryptData}, this.GetTransactionDetailOperationCompleted, userState);
    }
    
    private void OnGetTransactionDetailOperationCompleted(object arg) {
        if ((this.GetTransactionDetailCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetTransactionDetailCompleted(this, new GetTransactionDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]

public partial class VTCGWReponse {
    
    private string responseDataField;
    
    private string signField;
    
    /// <remarks/>
    public string ResponseData {
        get {
            return this.responseDataField;
        }
        set {
            this.responseDataField = value;
        }
    }
    
    /// <remarks/>
    public string Sign {
        get {
            return this.signField;
        }
        set {
            this.signField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]

public partial class MerchantSetAutoBillPaymentRequest {
    
    private string userIdField;
    
    private string registerIdField;
    
    private int notifyChanelField;
    
    private System.Nullable<int> notifyTimesField;
    
    private string endDateServiceField;
    
    private string customerNameField;
    
    private string customerAddressField;
    
    private string contactAddressField;
    
    private string contactNameField;
    
    private string contactPhoneField;
    
    private string contactEmailField;
    
    private decimal moneyMaxField;
    
    private int statusField;
    
    /// <remarks/>
    public string UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    public string RegisterId {
        get {
            return this.registerIdField;
        }
        set {
            this.registerIdField = value;
        }
    }
    
    /// <remarks/>
    public int NotifyChanel {
        get {
            return this.notifyChanelField;
        }
        set {
            this.notifyChanelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> NotifyTimes {
        get {
            return this.notifyTimesField;
        }
        set {
            this.notifyTimesField = value;
        }
    }
    
    /// <remarks/>
    public string EndDateService {
        get {
            return this.endDateServiceField;
        }
        set {
            this.endDateServiceField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerAddress {
        get {
            return this.customerAddressField;
        }
        set {
            this.customerAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ContactAddress {
        get {
            return this.contactAddressField;
        }
        set {
            this.contactAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <remarks/>
    public string ContactPhone {
        get {
            return this.contactPhoneField;
        }
        set {
            this.contactPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string ContactEmail {
        get {
            return this.contactEmailField;
        }
        set {
            this.contactEmailField = value;
        }
    }
    
    /// <remarks/>
    public decimal MoneyMax {
        get {
            return this.moneyMaxField;
        }
        set {
            this.moneyMaxField = value;
        }
    }
    
    /// <remarks/>
    public int Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]

public partial class AutoBillPaymentRequest {
    
    private string userIdField;
    
    private int notifyChanelField;
    
    private System.Nullable<int> notifyTimesField;
    
    private string endDateServiceField;
    
    private string serviceIdField;
    
    private string providerIdField;
    
    private string customerIdField;
    
    private string customerNameField;
    
    private string customerAddressField;
    
    private string contactAddressField;
    
    private string contactNameField;
    
    private string contactPhoneField;
    
    private string contactEmailField;
    
    private decimal moneyMaxField;
    
    /// <remarks/>
    public string UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    public int NotifyChanel {
        get {
            return this.notifyChanelField;
        }
        set {
            this.notifyChanelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> NotifyTimes {
        get {
            return this.notifyTimesField;
        }
        set {
            this.notifyTimesField = value;
        }
    }
    
    /// <remarks/>
    public string EndDateService {
        get {
            return this.endDateServiceField;
        }
        set {
            this.endDateServiceField = value;
        }
    }
    
    /// <remarks/>
    public string ServiceId {
        get {
            return this.serviceIdField;
        }
        set {
            this.serviceIdField = value;
        }
    }
    
    /// <remarks/>
    public string ProviderId {
        get {
            return this.providerIdField;
        }
        set {
            this.providerIdField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerId {
        get {
            return this.customerIdField;
        }
        set {
            this.customerIdField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerAddress {
        get {
            return this.customerAddressField;
        }
        set {
            this.customerAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ContactAddress {
        get {
            return this.contactAddressField;
        }
        set {
            this.contactAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <remarks/>
    public string ContactPhone {
        get {
            return this.contactPhoneField;
        }
        set {
            this.contactPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string ContactEmail {
        get {
            return this.contactEmailField;
        }
        set {
            this.contactEmailField = value;
        }
    }
    
    /// <remarks/>
    public decimal MoneyMax {
        get {
            return this.moneyMaxField;
        }
        set {
            this.moneyMaxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]

public partial class GetBillRegistedList {
    
    private System.Nullable<int> pageNoField;
    
    private System.Nullable<int> pageSizeField;
    
    private System.Nullable<long> registerIDField;
    
    private int registerTypeField;
    
    private string userIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> PageNo {
        get {
            return this.pageNoField;
        }
        set {
            this.pageNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> PageSize {
        get {
            return this.pageSizeField;
        }
        set {
            this.pageSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<long> RegisterID {
        get {
            return this.registerIDField;
        }
        set {
            this.registerIDField = value;
        }
    }
    
    /// <remarks/>
    public int RegisterType {
        get {
            return this.registerTypeField;
        }
        set {
            this.registerTypeField = value;
        }
    }
    
    /// <remarks/>
    public string UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]

public partial class MerchantAutoBillRemindRequest {
    
    private string userIdField;
    
    private int notifyChanelField;
    
    private System.Nullable<int> notifyTimesField;
    
    private string endDateServiceField;
    
    private string customerNameField;
    
    private string customerAddressField;
    
    private string contactAddressField;
    
    private string contactNameField;
    
    private string contactPhoneField;
    
    private string contactEmailField;
    
    private System.Nullable<long> registerIdField;
    
    private int statusField;
    
    /// <remarks/>
    public string UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    public int NotifyChanel {
        get {
            return this.notifyChanelField;
        }
        set {
            this.notifyChanelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> NotifyTimes {
        get {
            return this.notifyTimesField;
        }
        set {
            this.notifyTimesField = value;
        }
    }
    
    /// <remarks/>
    public string EndDateService {
        get {
            return this.endDateServiceField;
        }
        set {
            this.endDateServiceField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerAddress {
        get {
            return this.customerAddressField;
        }
        set {
            this.customerAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ContactAddress {
        get {
            return this.contactAddressField;
        }
        set {
            this.contactAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <remarks/>
    public string ContactPhone {
        get {
            return this.contactPhoneField;
        }
        set {
            this.contactPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string ContactEmail {
        get {
            return this.contactEmailField;
        }
        set {
            this.contactEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<long> RegisterId {
        get {
            return this.registerIdField;
        }
        set {
            this.registerIdField = value;
        }
    }
    
    /// <remarks/>
    public int Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]

public partial class AutoBillRemindRequest {
    
    private string userIdField;
    
    private int notifyChanelField;
    
    private System.Nullable<int> notifyTimesField;
    
    private string endDateServiceField;
    
    private string serviceIdField;
    
    private string providerIdField;
    
    private string customerIdField;
    
    private string customerNameField;
    
    private string customerAddressField;
    
    private string contactAddressField;
    
    private string contactNameField;
    
    private string contactPhoneField;
    
    private string contactEmailField;
    
    /// <remarks/>
    public string UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    public int NotifyChanel {
        get {
            return this.notifyChanelField;
        }
        set {
            this.notifyChanelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> NotifyTimes {
        get {
            return this.notifyTimesField;
        }
        set {
            this.notifyTimesField = value;
        }
    }
    
    /// <remarks/>
    public string EndDateService {
        get {
            return this.endDateServiceField;
        }
        set {
            this.endDateServiceField = value;
        }
    }
    
    /// <remarks/>
    public string ServiceId {
        get {
            return this.serviceIdField;
        }
        set {
            this.serviceIdField = value;
        }
    }
    
    /// <remarks/>
    public string ProviderId {
        get {
            return this.providerIdField;
        }
        set {
            this.providerIdField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerId {
        get {
            return this.customerIdField;
        }
        set {
            this.customerIdField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerAddress {
        get {
            return this.customerAddressField;
        }
        set {
            this.customerAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ContactAddress {
        get {
            return this.contactAddressField;
        }
        set {
            this.contactAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <remarks/>
    public string ContactPhone {
        get {
            return this.contactPhoneField;
        }
        set {
            this.contactPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string ContactEmail {
        get {
            return this.contactEmailField;
        }
        set {
            this.contactEmailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]

public partial class PayOfflineBillRequest {
    
    private string userIdField;
    
    private string serviceCodeField;
    
    private string serviceNameField;
    
    private string providerCodeField;
    
    private string providerNameField;
    
    private string customerIdField;
    
    private string customerNameField;
    
    private string contactAddressField;
    
    private string contactNameField;
    
    private string contactPhoneNumberField;
    
    private decimal moneyAmountField;
    
    private string systemTraceField;
    
    private string invoiceNoField;
    
    private string cardNoField;
    
    private string systemTraceExField;
    
    private string customerPhoneField;
    
    private string customerAddressField;
    
    private string transactionTimeField;
    
    /// <remarks/>
    public string UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    public string ServiceCode {
        get {
            return this.serviceCodeField;
        }
        set {
            this.serviceCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ServiceName {
        get {
            return this.serviceNameField;
        }
        set {
            this.serviceNameField = value;
        }
    }
    
    /// <remarks/>
    public string ProviderCode {
        get {
            return this.providerCodeField;
        }
        set {
            this.providerCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ProviderName {
        get {
            return this.providerNameField;
        }
        set {
            this.providerNameField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerId {
        get {
            return this.customerIdField;
        }
        set {
            this.customerIdField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    public string ContactAddress {
        get {
            return this.contactAddressField;
        }
        set {
            this.contactAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <remarks/>
    public string ContactPhoneNumber {
        get {
            return this.contactPhoneNumberField;
        }
        set {
            this.contactPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public decimal MoneyAmount {
        get {
            return this.moneyAmountField;
        }
        set {
            this.moneyAmountField = value;
        }
    }
    
    /// <remarks/>
    public string SystemTrace {
        get {
            return this.systemTraceField;
        }
        set {
            this.systemTraceField = value;
        }
    }
    
    /// <remarks/>
    public string InvoiceNo {
        get {
            return this.invoiceNoField;
        }
        set {
            this.invoiceNoField = value;
        }
    }
    
    /// <remarks/>
    public string CardNo {
        get {
            return this.cardNoField;
        }
        set {
            this.cardNoField = value;
        }
    }
    
    /// <remarks/>
    public string SystemTraceEx {
        get {
            return this.systemTraceExField;
        }
        set {
            this.systemTraceExField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerPhone {
        get {
            return this.customerPhoneField;
        }
        set {
            this.customerPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerAddress {
        get {
            return this.customerAddressField;
        }
        set {
            this.customerAddressField = value;
        }
    }
    
    /// <remarks/>
    public string TransactionTime {
        get {
            return this.transactionTimeField;
        }
        set {
            this.transactionTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]

public partial class BillInfoEx {
    
    private string billIdField;
    
    private string serviceIdField;
    
    private string providerIdField;
    
    private string monthField;
    
    private decimal moneyAmountField;
    
    private decimal paymentFeeField;
    
    private string customerNameField;
    
    private string addressField;
    
    private bool confirmIdField;
    
    private string serviceNameField;
    
    private string providerNameField;
    
    private System.Nullable<int> monthAmountField;
    
    private string renewalDateField;
    
    /// <remarks/>
    public string BillId {
        get {
            return this.billIdField;
        }
        set {
            this.billIdField = value;
        }
    }
    
    /// <remarks/>
    public string ServiceId {
        get {
            return this.serviceIdField;
        }
        set {
            this.serviceIdField = value;
        }
    }
    
    /// <remarks/>
    public string ProviderId {
        get {
            return this.providerIdField;
        }
        set {
            this.providerIdField = value;
        }
    }
    
    /// <remarks/>
    public string Month {
        get {
            return this.monthField;
        }
        set {
            this.monthField = value;
        }
    }
    
    /// <remarks/>
    public decimal MoneyAmount {
        get {
            return this.moneyAmountField;
        }
        set {
            this.moneyAmountField = value;
        }
    }
    
    /// <remarks/>
    public decimal PaymentFee {
        get {
            return this.paymentFeeField;
        }
        set {
            this.paymentFeeField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public bool ConfirmId {
        get {
            return this.confirmIdField;
        }
        set {
            this.confirmIdField = value;
        }
    }
    
    /// <remarks/>
    public string ServiceName {
        get {
            return this.serviceNameField;
        }
        set {
            this.serviceNameField = value;
        }
    }
    
    /// <remarks/>
    public string ProviderName {
        get {
            return this.providerNameField;
        }
        set {
            this.providerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> MonthAmount {
        get {
            return this.monthAmountField;
        }
        set {
            this.monthAmountField = value;
        }
    }
    
    /// <remarks/>
    public string RenewalDate {
        get {
            return this.renewalDateField;
        }
        set {
            this.renewalDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]

public partial class PayOnlineBillRequest {
    
    private string userIdField;
    
    private string contactAddressField;
    
    private string contactNameField;
    
    private string contactPhoneField;
    
    private string customerIdField;
    
    private string systemTraceExField;
    
    private string systemTraceField;
    
    private string invoiceNoField;
    
    private string cardNoField;
    
    private BillInfoEx[] billsField;
    
    private string transactionTimeField;
    
    private int paymentRuleField;
    
    /// <remarks/>
    public string UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    public string ContactAddress {
        get {
            return this.contactAddressField;
        }
        set {
            this.contactAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <remarks/>
    public string ContactPhone {
        get {
            return this.contactPhoneField;
        }
        set {
            this.contactPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerId {
        get {
            return this.customerIdField;
        }
        set {
            this.customerIdField = value;
        }
    }
    
    /// <remarks/>
    public string SystemTraceEx {
        get {
            return this.systemTraceExField;
        }
        set {
            this.systemTraceExField = value;
        }
    }
    
    /// <remarks/>
    public string SystemTrace {
        get {
            return this.systemTraceField;
        }
        set {
            this.systemTraceField = value;
        }
    }
    
    /// <remarks/>
    public string InvoiceNo {
        get {
            return this.invoiceNoField;
        }
        set {
            this.invoiceNoField = value;
        }
    }
    
    /// <remarks/>
    public string CardNo {
        get {
            return this.cardNoField;
        }
        set {
            this.cardNoField = value;
        }
    }
    
    /// <remarks/>
    public BillInfoEx[] Bills {
        get {
            return this.billsField;
        }
        set {
            this.billsField = value;
        }
    }
    
    /// <remarks/>
    public string TransactionTime {
        get {
            return this.transactionTimeField;
        }
        set {
            this.transactionTimeField = value;
        }
    }
    
    /// <remarks/>
    public int PaymentRule {
        get {
            return this.paymentRuleField;
        }
        set {
            this.paymentRuleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetBillsCompletedEventHandler(object sender, GetBillsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetBillsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetBillsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void OnlineBillPaymentCompletedEventHandler(object sender, OnlineBillPaymentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OnlineBillPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal OnlineBillPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void OnlineBillPayment4KioskCompletedEventHandler(object sender, OnlineBillPayment4KioskCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OnlineBillPayment4KioskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal OnlineBillPayment4KioskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void OfflineBillPaymentCompletedEventHandler(object sender, OfflineBillPaymentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OfflineBillPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal OfflineBillPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetUserTransactionListCompletedEventHandler(object sender, GetUserTransactionListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserTransactionListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetUserTransactionListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetTransactionStatusCompletedEventHandler(object sender, GetTransactionStatusCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetTransactionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetTransactionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void AddAutoBillRemindCompletedEventHandler(object sender, AddAutoBillRemindCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AddAutoBillRemindCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AddAutoBillRemindCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void UpdateAutoBillRemindCompletedEventHandler(object sender, UpdateAutoBillRemindCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateAutoBillRemindCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateAutoBillRemindCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetBillRegistedListCompletedEventHandler(object sender, GetBillRegistedListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetBillRegistedListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetBillRegistedListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void AddAutoBillPaymentCompletedEventHandler(object sender, AddAutoBillPaymentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AddAutoBillPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AddAutoBillPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void UpdateAutoBillPaymentCompletedEventHandler(object sender, UpdateAutoBillPaymentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateAutoBillPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateAutoBillPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetServicesCompletedEventHandler(object sender, GetServicesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetProvidersCompletedEventHandler(object sender, GetProvidersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetProvidersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetProvidersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetTransactionDetailCompletedEventHandler(object sender, GetTransactionDetailCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetTransactionDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetTransactionDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public VTCGWReponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((VTCGWReponse)(this.results[0]));
        }
    }
}
