//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 

namespace Paygate.Utility
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "WSeBankAPISoap", Namespace = "http://tempuri.org/")]
    public partial class WSeBankAPI : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ExecuteFunctionOperationCompleted;

        /// <remarks/>
        public WSeBankAPI()
        {
            this.Url = System.Configuration.ConfigurationManager.AppSettings["WS_eBankAPI_URL"];
                // "http://sandbox2.vtcebank.vn/eBankAPI/WSeBankAPI.asmx"
        }

        /// <remarks/>
        public event ExecuteFunctionCompletedEventHandler ExecuteFunctionCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteFunction",
            RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/",
            Use = System.Web.Services.Description.SoapBindingUse.Literal,
            ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExecuteFunction(string jSonData, string Sign)
        {
            object[] results = this.Invoke("ExecuteFunction", new object[]
                {
                    jSonData,
                    Sign
                });
            return ((string) (results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginExecuteFunction(string jSonData, string Sign, System.AsyncCallback callback,
                                                        object asyncState)
        {
            return this.BeginInvoke("ExecuteFunction", new object[]
                {
                    jSonData,
                    Sign
                }, callback, asyncState);
        }

        /// <remarks/>
        public string EndExecuteFunction(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string) (results[0]));
        }

        /// <remarks/>
        public void ExecuteFunctionAsync(string jSonData, string Sign)
        {
            this.ExecuteFunctionAsync(jSonData, Sign, null);
        }

        /// <remarks/>
        public void ExecuteFunctionAsync(string jSonData, string Sign, object userState)
        {
            if ((this.ExecuteFunctionOperationCompleted == null))
            {
                this.ExecuteFunctionOperationCompleted =
                    new System.Threading.SendOrPostCallback(this.OnExecuteFunctionOperationCompleted);
            }
            this.InvokeAsync("ExecuteFunction", new object[]
                {
                    jSonData,
                    Sign
                }, this.ExecuteFunctionOperationCompleted, userState);
        }

        private void OnExecuteFunctionOperationCompleted(object arg)
        {
            if ((this.ExecuteFunctionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs =
                    ((System.Web.Services.Protocols.InvokeCompletedEventArgs) (arg));
                this.ExecuteFunctionCompleted(this,
                                              new ExecuteFunctionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error,
                                                                                    invokeArgs.Cancelled,
                                                                                    invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ExecuteFunctionCompletedEventHandler(object sender, ExecuteFunctionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteFunctionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ExecuteFunctionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled,
                                                   object userState) :
                                                       base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string) (this.results[0]));
            }
        }
    }
}